"""
Constants for holding value of different messages.
"""
INVALID_LOOPR_KEY = "Loopr API key not provided"
INVALID_DATASET_TYPE = "Invalid dataset type provided"
INVALID_PROJECT_TYPE = "Invalid project type provided"
INVALID_ROW_TYPE = "Invalid row type provided"
relevancy_type_project = "relevancy"
object_detection_type_project = "object_detection"
categorization_type_project = "categorization"
ner_type_project = "ner"
segmentation_project = "segmentation"
ocr_type_project = "ocr"
image_type_dataset = "image"
sku_type_dataset = "sku"
text_type_dataset = "text"
