dist: xenial
language: python
env:
  global:
    - secure: ERx1gbYkgBVfmydtf3uQlkzIEH3Qb23Od3qr/nRNkl1ys5pKsZ2fYGiSXO6xVF7YXA/8Wb4KBvIUrVevuDWxR0bdLh3Iv8YNt6Prscz/sWDTGk/U8i+nlLagB/yttTcbEPz7BHP/V6EwHpfDBtE0r8h/5JVNydaZq1en0OB/5x96cFGlzbyj+jIJaGFznoLTBCfR9aiv7DsxlPhpsLRSDrDbhpM3Z/u2MXlNTEstPF4e8OoGvX1xMt8XA8SPk1sKAqCn2RdBB1ftkE07eyKK4XuAkfwo1Q5fQrR3gIL5Wb6RHNAhy3OWEqp6nFuoC8v4PzGmTmnMwnenzt1Q+uE4yGZ0KQgbw1RnCXyvj8U1RkEgdSfNJX45j2kOVD5rc9XzY+hNIhIrihD4IEAA+rJ30dITbL//QWxYDzhoPk/vB4hSdjF2ezEkxQwJIaDh5g6EKh1wPvjD05QSGj33kaCJ9SHgauI37kl9Od0mbelnPQL1tIpiAnrpvj9ARANjCurwNyrc4SfEzEXN12dJ6Nq1KeY8nAb5JD22jGBR9URVquERyGod21DUHS13BdC15TsW44sGz20IMSdKNUX2qRyQXYIqqWfRg+SJJFbnSRZvcfIHXEAE09rxc4KakEuIgvkyrYCpmkMchd4TsN4fcEOudMVUaxLQd8yge4udpgN8dkc=
    - secure: Ge+fCyMm9Dl8+fp/RAuspaZljxmZT0XWGep0oD+oWTv5aGIDvQ/jmCCcP7639n1TqAktau/73xsGwX8lmPxjhNnP03kpzOya9ktQbnJ0tKlcRZsPNeUcbGfx3l03ms0P7Z6If0ZSUPXa89oK3cHg+y01RAKqBFANfSC7WyAhyUffHTflt/Ze055Xuvp24BKa4fEQvQIGyX5u0dXv92R5BvpZaiQOoI0MyVRd6F8r1RUxBYNiBbHgWxiTFqKbaGe1YC1h37qPqzqMBIGgDpVtHaSX3cIBe3qDwZrs0xdZf2g2Yf2XNEs24J0EP+R7G0LtpWjIxRcm7ASfYaHg3zm1wCOR9rWkQcSKkNES62a5AnMMVxKPmF7gAqmW2g5iEj70sZJM/soteN8MGQmFItLFjS7Iyx8sHjUbRkqFv4kUhH//0ZfoA0iWVyvXPuvyoR8PsNCNalhY4mi9kMOqZAbJF8N/ZI+pVnLk3dEb+WhZ1CaDtkNC0cO5Modbl32BwOoQ7EU3nrn9su6rVg26dHcGSvHqFJ5N4eXOwiKpu8bpSYM9IZyQm3Nmipa/e1ec20VwSpXDORTjSIrSWgb34mp0QK7OcqYtF1AU7vHSbagvp3PevvpOLdlwkPN4wgfYOx+/Cy8gsQvFfLwE61BzMfeM2OKnmmiNWz0hJyM1BvIuA1E=
    - secure: Jte56OHOgzzojKUEpKqQiaGY4LdLUBxTYW6ukCQd1qhOtsvbD71Y2xmqaRrROZYue6uyu7mbPROGmpSWMzLq8+Lj5eDtY4R11Ree/cLdPpV5AtNgQcS5vgVn2YxdAbSlWGG0RVOrQx2Ha17N9URTL0jguNqfz1Fnwvym6ln+7Z4jPiu/uNqkcrN7xQJWxRnkq4dob7lIq5RR2Z+4AsphqGdOgh8MzdrAWgXgTb2Ajz7jYrfuvkoacO991Wptm/3UkMW2Jh8F5OZmYinNvAej7OgS6Z0uqBFLrP3Ig3FfzjbjASBnkGkrIDW6gL1J4r6Het3BuhUD9nO0yLtv05SKIEUGLAMSOb9i7/INgz9pfYRi6u+bIhmZpLqLo8xHoLuBoIsLG0GVv4MtsZN7Z4RJ/IStKeMWlj6nAZ4pgbmEGp6S9LZ19nKaO8pYMT7opVd/lqXB6C/IIgosJHvfsV8+ueN3QWH65qjZgK9G+Wgx7GlZ0PGNIrebde/eHLPlgrG4ezmG4Yhpxzf+fNpe2YCNFxM7ldBPWa6sx80l8UQD+XfLKvZmgmZid+JFlc9OEXGwQoqT+IJ8zvZFPGBXZm85KbFsNAjD2kIN9EmI6ap+wwE/fdqHi4JUtk6aU6zfYeSjKbKn8zwWi7388lbKEQf1YR/838a//wDAcQJm4+DxNJ4=
before_install:
  - pip3 install poetry
  - poetry config virtualenvs.create false
  - export LOOPR_PYTHON_SDK_TEST_ENV=dev
  - export LOOPR_PROD_URL=https://api.loopr.ai/

install:
  - poetry install
stages:
  - name: "lint"
    if: type = push
  - name: "pytest 3.6"
    if: type = push
  - name: "pytest 3.7"
    if: type = push
  - name: "pytest 3.8"
    if: type = push
  - name: "build and publish"
    if: tag IS present
jobs:
  include:
    - stage: "lint"
      name: "lint using python 3.6 "
      python: 3.6
      script:
        - make lint
    - name: "lint using python 3.7 "
      python: 3.7
      script:
        - make lint
    - name: "lint using python 3.8 "
      python: 3.8
      script:
        - make lint
    - stage: "pytest 3.6"
      name: "test using python 3.6 "
      python: 3.6
      script:
        - make test
    - stage: "pytest 3.7"
      name: "test using python 3.7 "
      python: 3.7
      script:
        - make test
    - stage: "pytest 3.8"
      name: "test using python 3.8 "
      python: 3.8
      script:
        - make test
    - stage: "build and publish"
      python:
        - 3.8
      script:
        - poetry build
        - twine upload --skip-existing dist/*.tar.gz -u __token__ -p $PYPI_TOKEN

