dist: xenial
language: python
env:
  global:
    - secure: ERx1gbYkgBVfmydtf3uQlkzIEH3Qb23Od3qr/nRNkl1ys5pKsZ2fYGiSXO6xVF7YXA/8Wb4KBvIUrVevuDWxR0bdLh3Iv8YNt6Prscz/sWDTGk/U8i+nlLagB/yttTcbEPz7BHP/V6EwHpfDBtE0r8h/5JVNydaZq1en0OB/5x96cFGlzbyj+jIJaGFznoLTBCfR9aiv7DsxlPhpsLRSDrDbhpM3Z/u2MXlNTEstPF4e8OoGvX1xMt8XA8SPk1sKAqCn2RdBB1ftkE07eyKK4XuAkfwo1Q5fQrR3gIL5Wb6RHNAhy3OWEqp6nFuoC8v4PzGmTmnMwnenzt1Q+uE4yGZ0KQgbw1RnCXyvj8U1RkEgdSfNJX45j2kOVD5rc9XzY+hNIhIrihD4IEAA+rJ30dITbL//QWxYDzhoPk/vB4hSdjF2ezEkxQwJIaDh5g6EKh1wPvjD05QSGj33kaCJ9SHgauI37kl9Od0mbelnPQL1tIpiAnrpvj9ARANjCurwNyrc4SfEzEXN12dJ6Nq1KeY8nAb5JD22jGBR9URVquERyGod21DUHS13BdC15TsW44sGz20IMSdKNUX2qRyQXYIqqWfRg+SJJFbnSRZvcfIHXEAE09rxc4KakEuIgvkyrYCpmkMchd4TsN4fcEOudMVUaxLQd8yge4udpgN8dkc=
    - secure: Ge+fCyMm9Dl8+fp/RAuspaZljxmZT0XWGep0oD+oWTv5aGIDvQ/jmCCcP7639n1TqAktau/73xsGwX8lmPxjhNnP03kpzOya9ktQbnJ0tKlcRZsPNeUcbGfx3l03ms0P7Z6If0ZSUPXa89oK3cHg+y01RAKqBFANfSC7WyAhyUffHTflt/Ze055Xuvp24BKa4fEQvQIGyX5u0dXv92R5BvpZaiQOoI0MyVRd6F8r1RUxBYNiBbHgWxiTFqKbaGe1YC1h37qPqzqMBIGgDpVtHaSX3cIBe3qDwZrs0xdZf2g2Yf2XNEs24J0EP+R7G0LtpWjIxRcm7ASfYaHg3zm1wCOR9rWkQcSKkNES62a5AnMMVxKPmF7gAqmW2g5iEj70sZJM/soteN8MGQmFItLFjS7Iyx8sHjUbRkqFv4kUhH//0ZfoA0iWVyvXPuvyoR8PsNCNalhY4mi9kMOqZAbJF8N/ZI+pVnLk3dEb+WhZ1CaDtkNC0cO5Modbl32BwOoQ7EU3nrn9su6rVg26dHcGSvHqFJ5N4eXOwiKpu8bpSYM9IZyQm3Nmipa/e1ec20VwSpXDORTjSIrSWgb34mp0QK7OcqYtF1AU7vHSbagvp3PevvpOLdlwkPN4wgfYOx+/Cy8gsQvFfLwE61BzMfeM2OKnmmiNWz0hJyM1BvIuA1E=

before_install:
  - pip3 install poetry
  - poetry config virtualenvs.create false
  - export LOOPR_PYTHON_SDK_TEST_ENV=dev
  - export LOOPR_DEV_URL=https://dev-api.loopr.ai/
  - export LOOPR_PROD_URL=https://api.loopr.ai/

install:
  - poetry install
stages:
  - name: "lint and test"
    if: type = push
  - name: "build and publish"
    if: tag IS present
jobs:
  include:
    - stage: "lint and test"
      name: "lint using python 3.6 "
      python: 3.6
      script:
        - make lint
    - name: "lint using python 3.7 "
      python: 3.7
      script:
        - make lint
    - name: "lint using python 3.8 "
      python: 3.8
      script:
        - make lint
    - name: "test using python 3.6 "
      python: 3.6
      script:
        - make test
    - name: "test using python 3.7 "
      python: 3.7
      script:
        - make test
    - name: "test using python 3.8 "
      python: 3.8
      script:
        - make test
    - stage: "build and publish"
      python:
        - 3.8
      script:
        - poetry build
        - twine upload --skip-existing dist/* -u __token__ -p $PYPI_TOKEN

